### ISSUE TITLE
Texture functionality

### ISSUE THREAD

**Issue by levigoessling** [Julian-Vos/godot-scripts#1]
Polygon2Ds prior to calling destruct on the grassy polygon from the white polygon, passing (polygon, global_position).

![image](https://github.com/user-attachments/assets/0fcd27c3-09e4-405a-b092-86c4dbe10afa)

After calling destruct:

![image](https://github.com/user-attachments/assets/fdbc5d9e-5510-4144-b62b-2722043e8881)

The difference collision shape functions perfectly but the texture is visibly distorted.

With textures off:

Before destruct
![image](https://github.com/user-attachments/assets/39e2fdec-10b9-4617-9635-a1f07582126b)

After destruct
![image](https://github.com/user-attachments/assets/67e21ca7-cb95-41e0-b5e9-1262e14035d6)

Changing simplification value does not significantly change result.

I'm not super familiar with Git so thanks for your patience if I have submitted this incorrectly. Levi

**Comment by Julian-Vos** [comment]
Hello! Thank you for your report. I don't think the texture is the problem (textures work in my example https://github.com/Julian-Vos/example-DestructiblePolygon2D-4). In the last screenshot it seems to connect the left vertex of the hole with a vertex near the bottom instead of the top left one... unfortunately I cannot reproduce it 🤔 Maybe there is an error in your vertices (Data Polygon)? If you are able to share a reproduction project I will look into it further.

**Comment by levigoessling** [comment]
Hey Julian, thanks for getting back to me!

It could be the complexity of the Polygon2D which I have gotten Godot to
create from Sprite2D (the built in feature). As you can see the texture is
pixel art with a lot of vertices. And yes, definitely something is going on
even without a texture assigned, perhaps I mislabelled as it just appears
to have different effects to the texture than expected.

I'll send the project to you soon.
Thank you

Levi

**Comment by levigoessling** [comment]
Hey Julian, attached is the project file. Please try debug in the main scene. I have the destruct set to be called after about 3 seconds and a player character to test the collision with.
[Uploading Project Copy.zip…]()

**Comment by levigoessling** [comment]
Hey Julian, what's the best way to get the project to you? I tried zipping up the project's contents but it doesnt seem to upload here, and my email blocks it.
Levi

**Comment by Julian-Vos** [comment]
Hey, uploading the .zip here should work in theory (see https://github.com/Julian-Vos/asset-library-MapCamera2D-4/issues/5 for example), but otherwise you could try something like Google Drive or WeTransfer?

**Comment by levigoessling** [comment]
Hey Julian, uploaded the zip to Drive. Let me know if any issues.

https://drive.google.com/file/d/1cq2z64k1o_4OuHHvjbqrQ5vYlqlKndIJ/view?usp=sharing

The debug is setup to call the destruct on the terrain after a few seconds. Thanks.

**Comment by Julian-Vos** [comment]
Thanks! I've found a solution. Apparently, "create from Sprite2D" not only sets the data property  `polygon`, but also `uv` and `polygons`. My script doesn't expect this, so when it modifies `polygon`, then `uv` and `polygons` aren't updated correspondingly and that looks wrong. Extending the script to update  `uv` and `polygons` as well would be very complicated. However, you can simply remove (clear) `uv` and `polygons` from your Polygon2D, and instead use the `texture_offset` property to position the texture within the polygon: you should use `x: 104, y: 16.5` (half the texture's dimensions).

**Comment by levigoessling** [comment]
Thanks Julian for spending your own time on this and finding a solution. 
I did as you described and now your script integrates with that polygon perfectly.
